import { Project } from '../types';

export const projects: Project[] = [
  {
    id: 1,
    title: 'AI Detector',
    category: 'Text Classification',
    description: 'AI Detector is a machine learning tool that checks if a text was written by a human or generated by AI.',
    imageUrl: '/cover_aitext.png',
    link: 'https://github.com/vehnie/AIDetector',
    tags: ['NLP', 'Supervised ML']
  },
  {
    id: 2,
    title: 'DRL Path Finding in Graphs',
    category: 'Algorithms & Optimization',
    description: 'Graph Pathfinding is a project that uses algorithms like A*, Dijkstra, and reinforcement learning to find the best path in randomly generated graphs.',
    imageUrl: '/cover_graphs.png',
    link: 'https://github.com/vehnie/DRLPathFindingGraphs',
    tags: ['Graphs Theory', 'Reinforcement Learning']
  },
  {
    id: 3,
    title: 'Fire Detector',
    category: 'Computer Vision',
    description: 'Fire Detector is a computer vision system that uses a ResNet-50 model and temperature data to detect fires in real time.',
    imageUrl: '/cover_fire.png',
    link: 'https://github.com/vehnie/FireDetector',
    tags: ['Computer Vision', 'Supervised ML']
  },
  {
    id: 4,
    title: 'Neroes ML Model',
    category: 'Bio Technology',
    description: 'Anxiety Detection is a machine learning project focused on identifying patterns related to anxiety using behavioral and biometric data. The project involved setting clear objectives, data analysis, and developing an effective predictive model.',
    imageUrl: '/cover_anxiety.png',
    link: 'https://neroes.tech/pt/',
    tags: ['Neuroscience', 'Non Supervised ML']
  },
  {
    id: 5,
    title: 'Predictive Property Pricing',
    category: 'Machine Learning',
    description: 'Property Price Predictor is a machine learning model that estimates property prices in Portugal for sales, rentals, and vacation listings.',
    imageUrl: '/cover_house.png',
    link: 'https://github.com/vehnie/PredictivePropertyPricing',
    tags: ['Data Science', 'Supervised Ml']
  }
];